apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dev-optimized
spec:
  template:
    metadata:
      labels:
        node.kubernetes.io/managed-by: karpenter
        environment: dev
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: dev-optimized

      requirements:
        # ARM64 only (Graviton - 20% cheaper)
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        
        # Linux only
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        
        # Spot only (70% cheaper than On-Demand)
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        
        # T-family instances (burstable, cost-effective)
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        
        # Generation >= 3 (t4g and newer)
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]

  # Limits - prevent runaway costs
  limits:
    cpu: "100"
    memory: 200Gi

  # Disruption - AGGRESSIVE for dev
  disruption:
    # Consolidate underutilized nodes (not just empty)
    consolidationPolicy: WhenUnderutilized
    
    # Fast consolidation (30s vs 1min default)
    consolidateAfter: 30s
    
    # Expire nodes after 7 days (security + AMI updates)
    expireAfter: 168h
    
    # Limit disruption to 10% of nodes at once
    budgets:
      - nodes: "10%"

  # Priority (lower = higher priority)
  weight: 10
